version: '3'

services:
  app:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - '8080:8080'

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
