spring:
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 24
    refresh: 730