spring:
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cache:
    type: redis
    cache-names: redis-cache
security:
  jwt:
    secret: cmdramVybGtqZ2xkZmthamdsa2FkZmpnbGo0aWo0aW9najQwOThnajQwdzlqZzIzLXI=
    access: 24
    refresh: 730