spring:
  datasource:
    url: jdbc:h2:mem:tasklist
    username: tasklist
    password: 123
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:demo_data.sql
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml

security:
  jwt:
    secret: cmdramVybGtqZ2xkZmthamdsa2FkZmpnbGo0aWo0aW9najQwOThnajQwdzlqZzIzLXI=
    access: 24
    refresh: 730