spring:
  datasource:
    url: jdbc:h2:mem:tasklist
    username: tasklist
    password: 123
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: aGdqZ2poanZnaHZoZ2NoY3Y=

security:
  jwt:
    secret: cmdramVybGtqZ2xkZmthamdsa2FkZmpnbGo0aWo0aW9najQwOThnajQwdzlqZzIzLXI=
    access: 24
    refresh: 730