-- drop table if exists tasks,users;
-- create schema if not exists tasklist;

create table if not exists users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(255) NOT NULL,
    username varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL
);

create table if not exists tasks
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           varchar(255) NOT NULL,
    description     varchar(255),
    status          varchar(255) NOT NULL,
    expiration_date TIMESTAMP default null,
    user_id         BIGINT,
    CONSTRAINT fk_users_tasks foreign key (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION
);

create table if not exists users_roles
(
    user_id BIGINT       NOT NULL,
    role    varchar(255) NOT NULL,
    primary key (user_id, role),
    constraint fk_users_roles_users foreign key (user_id) references users (id) on delete cascade on update no action
);